[package]
name = "lotlinx"
version = "0.1.0"
authors = ["Victor I. Afolabi <vafolabi@lotlinx.com>"]
edition = "2018"
description = "Lotlinx command line utility"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/victor-iyi/lotlinx"
repository = "https://github.com/victor-iyi/lotlinx"
keywords = ["lotlinx", "lotlinx-cli"]
categories = ["command-line-utilities"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lotlinx"
path = "src/lib.rs"

[[bin]]
name = "lotlinx"
path = "src/main.rs"

[dependencies]
clap = { version = "*", features = ["yaml"] }